# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('viewed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, max_length=20, null=True)),
                ('pos', models.CharField(blank=True, max_length=20, null=True)),
                ('cores', models.PositiveIntegerField(blank=True, null=True)),
                ('ram', models.PositiveIntegerField(blank=True, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('kernel', models.CharField(blank=True, max_length=50, null=True)),
                ('k_release', models.CharField(blank=True, max_length=50, null=True)),
                ('processor', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('partition', models.CharField(blank=True, max_length=50, null=True)),
                ('part_usage', models.FloatField(blank=True, null=True)),
                ('procs', models.PositiveIntegerField(blank=True, null=True)),
                ('load5', models.FloatField(blank=True, null=True)),
                ('load15', models.FloatField(blank=True, null=True)),
                ('ram_prc', models.FloatField(blank=True, null=True)),
                ('cpu_pcpu', models.FloatField(blank=True, null=True)),
                ('sync_dif', models.CharField(blank=True, max_length=50, null=True)),
                ('uptime_seg', models.FloatField(blank=True, null=True)),
                ('uptime_str', models.CharField(blank=True, max_length=50, null=True)),
                ('ram_top_proc', models.CharField(blank=True, max_length=200, null=True)),
                ('ram_top_pmem', models.FloatField(blank=True, null=True)),
                ('cpu_proc_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cpu_proc_pcpu', models.FloatField(blank=True, null=True)),
                ('fans', models.TextField(default='No Data')),
                ('temperature', models.TextField(default='No Data')),
                ('dimms', models.TextField(default='No Data')),
                ('server_desc', models.TextField(default='No Data')),
                ('power_suply', models.TextField(default='No Data')),
                ('raid', models.TextField(default='No Data')),
                ('screen', models.TextField(default='No Data')),
                ('dmi', models.TextField(default='No Data')),
                ('temp_stat', models.TextField(default='N/A')),
                ('fans_stat', models.TextField(default='N/A')),
                ('proc_stat', models.TextField(default='N/A')),
                ('pwr_stat', models.TextField(default='N/A')),
                ('dimm_stat', models.TextField(default='N/A')),
                ('ld_stat', models.TextField(default='N/A')),
                ('pd_stat', models.TextField(default='N/A')),
                ('video_usage', models.TextField(default='N/A')),
                ('gpu_temp', models.TextField(default='N/A')),
                ('connected', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.CharField(blank=True, max_length=50, null=True)),
                ('part_usage', models.FloatField(blank=True, null=True)),
                ('procs', models.PositiveIntegerField(blank=True)),
                ('load5', models.FloatField(blank=True)),
                ('load15', models.FloatField(blank=True)),
                ('ram_prc', models.FloatField(blank=True)),
                ('cpu_pcpu', models.FloatField(blank=True)),
                ('uptime_seg', models.FloatField(blank=True)),
                ('uptime_str', models.CharField(blank=True, max_length=50)),
                ('ram_top_proc', models.CharField(blank=True, max_length=200)),
                ('ram_top_pmem', models.FloatField(blank=True)),
                ('cpu_proc_name', models.CharField(blank=True, max_length=200)),
                ('cpu_proc_pcpu', models.FloatField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Node')),
            ],
        ),
        migrations.AddField(
            model_name='networknotification',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Node'),
        ),
    ]
