# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20160302_0706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='cpu',
            new_name='platform',
        ),
        migrations.RemoveField(
            model_name='node',
            name='machine',
        ),
    ]
