# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20160302_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancehistory',
            name='part_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancehistory',
            name='partition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
