# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20160302_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='connected',
            field=models.BooleanField(default=True),
        ),
    ]
