# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_node_connected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='sync_dif',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
